import React from 'react';
import { 
  Cake, ShieldCheck, Tv, CalendarDays, 
  CreditCard, Car, FileText, User, 
  Phone, Globe, Tv as TvSub, ShoppingBag,
  Stethoscope, Briefcase, Users, Heart, StickyNote
} from 'lucide-react';
import { CategoryType, SubCategoryType, LanguageCode } from './types';

export const LANGUAGE_NAMES: Record<LanguageCode, string> = {
  en: 'English',
  es: 'Español'
};

export const TRANSLATIONS: Record<string, any> = {
  en: {
    appName: 'MY DAYS',
    andExpenses: '& EXPENSES',
    expensesBtn: 'EXPENSES',
    allImportant: 'MY EXPENSES',
    dashboard: 'HOME',
    categories: 'CATEGORIES',
    calendar: 'CALENDAR',
    settings: 'SETTINGS',
    upcoming: 'COMING UP',
    addDate: 'NEW REMINDER',
    addNote: 'NEW NOTE',
    noDates: 'ALL SET! NO PENDING DATES',
    save: 'SAVE',
    copyText: 'COPY TEXT',
    title: 'NAME',
    date: 'DATE',
    time: 'TIME',
    notes: 'NOTES...',
    birthdays: 'BIRTHDAYS',
    documents: 'DOCUMENTS',
    homeDocuments: 'DOCUMENTS',
    subscriptions: 'SUBSCRIPTIONS',
    appointments: 'APPOINTMENTS',
    theme: 'DARK MODE',
    autoDelete: 'AUTO-DELETE EXPIRED',
    language: 'LANGUAGE',
    contactsLabel: 'IMPORT\nCONTACTS',
    googleLogin: 'Sign in with Google',
    syncActive: 'Cloud Sync Active',
    lastSync: 'Synced',
    justNow: 'Just now',
    syncing: 'Syncing...',
    sub_dni: 'Personal',
    sub_bank: 'Cards',
    sub_vehicle: 'Vehicles',
    sub_insur: 'Taxes',
    sub_phone: 'Telephony',
    sub_web: 'Web / App',
    sub_tv: 'TV / Wifi',
    sub_stores: 'Stores / Clubs',
    sub_med: 'Medical',
    sub_work: 'Work',
    sub_friends: 'Personal',
    sub_fam: 'Family',
    finalized: 'EXPIRED',
    selectLanguage: 'CHOOSE LANGUAGE',
    myAccount: 'MY ACCOUNT',
    manageData: 'Manage your data & sync',
    secureDates: 'Secure your dates by syncing with Google',
    currentPlan: 'CURRENT PLAN',
    freePlan: 'FREE PLAN',
    goldPlan: 'MY DAYS GOLD',
    upgradeToGold: 'UPGRADE TO GOLD',
    saveChanges: 'SAVE CHANGES',
    howMuchAdvance: 'WHEN SHOULD WE NOTIFY YOU?',
    alertPrefix: 'REMINDER:',
    beforeSuffix: 'BEFORE',
    writeDetails: 'Add any extra details here...',
    repeatYearly: 'Remember every year',
    goldBannerTitle: 'MY DAYS GOLD',
    goldBannerText: 'UNLOCK THE FULL POWER AND REMOVE ADS FOREVER.',
    unlockPremium: 'UNLOCK PREMIUM',
    oneTimePayment: 'One-time payment forever',
    activateFor: 'ACTIVATE FOR 7.99 USD',
    lifetimeSub: 'LIFETIME SUBSCRIPTION',
    goldFeatures: [
      "Daily and monthly expense control",
      "Email Alerts & Device Notifications",
      "Unlimited cloud sync",
      "No ads or interruptions",
      "Auto-delete expired events",
      "Unlimited contact import",
      "Custom themes (Dark Mode)",
      "Add reminders from calendar"
    ],
    eventsForDay: 'Events for',
    noEventsToday: 'Nothing scheduled for today',
    deleteConfirm: 'DELETE REMINDER?',
    autoDeleteConfirm: 'ENABLE AUTO-DELETE FOR PAST EVENTS?',
    importContactsConfirm: 'WANT TO IMPORT BIRTHDAYS FROM YOUR CONTACTS?',
    emailConfirmTitle: 'EMAIL ALERTS PERMISSION',
    emailConfirmText: 'Do you authorize My Days to send alerts to your registered email?',
    emailConfirmNote: 'Device notifications will remain active.',
    yes: 'YES',
    no: 'NO',
    askFriends: 'MY FRIENDS\' BIRTHDAYS',
    askFriendsSub: 'Copy the text and send it to your friends',
    copiedToClipboard: 'Text copied!',
    yourBirthday: 'CONFIRM YOUR BIRTHDAY DATE',
    thanks: 'THANKS 🎂',
    happyBirthday: 'HAPPY BIRTHDAY!',
    version: 'VERSION',
    min_suffix: 'MINUTES',
    hour_suffix: 'HOURS',
    day_suffix: 'DAY',
    days_suffix: 'DAYS',
    reminderDetails: 'REMINDER DETAILS',
    desc_BIRTHDAYS: "Birthdays, anniversaries, or special dates to celebrate.",
    desc_DOCUMENTS: "Expiration date for documents and legal items.",
    desc_SUBSCRIPTIONS: "Renewal of phone, web, tv or any store club service.",
    desc_APPOINTMENTS: "Medical appointments, work meetings or reunions.",
    desc_NOTES: "Daily notes, shopping list, general annotations",
    chooseColor: 'CHOOSE NOTE COLOR',
    audioNote: 'AUDIO NOTE',
    addFile: 'ADD FILE',
    attachedFile: 'ATTACHED FILE',
    deleteFileTitle: 'DELETE FILE?',
    deleteFileConfirm: 'ARE YOU SURE YOU WANT TO DELETE THIS FILE?',
    deleteFileFinal: 'CONFIRM FINAL DELETION',
    noFile: 'NO ATTACHMENT',
    record: 'RECORD',
    stop: 'STOP',
    play: 'PLAY',
    recording: 'RECORDING...',
    max30s: 'Max 30 seconds',
    desc_DNI_PASAPORTE: "Expiration date for ID, personal identification, or any legal document.",
    desc_BANCO_TARJETAS: "Credit or debit cards expiration date.\nIMPORTANT: For security reasons, do not enter the full card number.",
    desc_VEHICULOS: "Technical inspections, oil changes, or vehicle insurance.",
    desc_SEGUROS: "Payment of taxes, rates, periodic contributions or insurance.",
    desc_TELEFONIA: "Renewal of phone contracts or internet services.",
    desc_WEB_APP: "Subscriptions to web services, apps, or digital entertainment.",
    desc_TV_WIFI: "Streaming platforms, cable TV, or Wi-Fi services.",
    desc_TIENDAS_CLUBS: "Loyalty cards, gym memberships, or club fees.",
    desc_MEDICAS: "Medical appointments, dentist visits, or health specialists.",
    desc_TRABAJO: "Meetings, deadlines, work, school or academic events.",
    desc_AMIGOS: "Friends, hair salon, gym or trips.",
    desc_FAMILIARES: "Family events, celebrations, or reunions.",
    cardsNewReminder: 'CARDS NEW REMINDER',
    dailyExpenses: 'NEW EXPENSE',
    viewMyExpenses: 'VIEW MY EXPENSES',
    currencyLabel: 'Currency',
    amount: 'AMOUNT',
    category: 'CATEGORY',
    expensesOf: 'EXPENSES OF',
    totalMonthly: 'MONTHLY TOTAL',
    expenseCategories: {
      SUPERMARKET: 'Supermarket',
      RESTAURANT: 'Restaurant',
      SHOPPING: 'Shopping',
      WORK: 'Work',
      ENTERTAINMENT: 'Entertainment',
      TRANSPORT: 'Transport',
      HOME: 'Home',
      PETS: 'Pets',
      FUEL: 'Fuel',
      VEHICLES: 'Vehicles',
      SERVICES: 'Services',
      HEALTH: 'Health',
      OTHERS: 'Others'
    },
    purchaseHistory: 'PURCHASE HISTORY',
    transactionId: 'TRANSACTION ID',
    purchaseDate: 'PURCHASE DATE',
    notifyMethod: 'MAIL NOTIFICATION',
    pushNotify: 'DEVICE NOTIFICATION',
    emailNotify: 'EMAIL ALERT',
    profilePhoto: 'PROFILE PHOTO',
    uploadPhoto: 'UPLOAD PHOTO',
    photoResolutionNote: 'The photo is saved locally in your browser cache.',
    sameDay: 'SAME DAY',
    generalNotifTime: 'NOTIF. TIME',
    generalNotifTimeDesc: 'Choose the time you want to receive your alerts on the corresponding days.',
    selectTime: 'SELECT TIME',
    exportExpenses: 'EXPORT EXPENSES',
    selectFormat: 'SELECT EXPORT FORMAT',
    excelFormat: 'EXCEL / CSV',
    pdfFormat: 'PDF DOCUMENT',
    textFormat: 'TEXT FILE',
    other: 'OTHER',
    info: 'INFO',
    seeTutorial: 'SEE TUTORIAL'
  },
  es: {
    appName: 'MIS FECHAS',
    andExpenses: '& GASTOS',
    expensesBtn: 'GASTOS',
    allImportant: 'MIS GASTOS',
    dashboard: 'INICIO',
    categories: 'CATEGORÍAS',
    calendar: 'CALENDARIO',
    settings: 'AJUSTES',
    upcoming: 'PRÓXIMOS',
    addDate: 'NUEVO RECORDATORIO',
    addNote: 'NUEVA NOTA',
    noDates: '¡TODO LISTO! SIN FECHAS PENDIENTES',
    save: 'GUARDAR',
    copyText: 'COPIAR TEXTO',
    title: 'NOMBRE',
    date: 'FECHA',
    time: 'HORA',
    notes: 'NOTAS...',
    birthdays: 'CUMPLEAÑOS',
    documents: 'DOCUMENTOS',
    homeDocuments: 'DOCUMENTOS',
    subscriptions: 'SUSCRIPCIONES',
    appointments: 'CITAS',
    theme: 'MODO OSCURO',
    autoDelete: 'AUTO-BORRAR PASADOS',
    language: 'IDIOMA',
    contactsLabel: 'IMPORTAR\nCONTACTOS',
    googleLogin: 'Inicia sesión con Google',
    syncActive: 'Sincronización Activa',
    lastSync: 'Sincronizado',
    justNow: 'Ahora',
    syncing: 'Sincronizando...',
    sub_dni: 'Personal',
    sub_bank: 'Tarjetas',
    sub_vehicle: 'Vehículos',
    sub_insur: 'Impuestos',
    sub_phone: 'Telefonía',
    sub_web: 'Web / App',
    sub_tv: 'TV / Wifi',
    sub_stores: 'Tiendas / Clubs',
    sub_med: 'Médicas',
    sub_work: 'Trabajo',
    sub_friends: 'Personales',
    sub_fam: 'Familia',
    finalized: 'VENCIDO',
    selectLanguage: 'ELIGE IDIOMA',
    myAccount: 'MI CUENTA',
    manageData: 'Gestiona tus datos y sincronización',
    secureDates: 'Asegura tus fechas sincronizando con Google',
    currentPlan: 'PLAN ACTUAL',
    freePlan: 'PLAN GRATUITO',
    goldPlan: 'MY DAYS GOLD',
    upgradeToGold: 'MEJORAR A GOLD',
    saveChanges: 'GUARDAR CAMBIOS',
    howMuchAdvance: '¿CUÁNDO TE AVISAMOS?',
    alertPrefix: 'AVISO:',
    beforeSuffix: 'ANTES',
    writeDetails: 'Escribe aquí cualquier detalle extra...',
    repeatYearly: 'Recordar cada año',
    goldBannerTitle: 'MY DAYS GOLD',
    goldBannerText: 'DESBLOQUEA TODO EL PODER Y ELIMINA ANUNCIOS PARA SIEMPRE.',
    unlockPremium: 'DESBLOQUEAR PREMIUM',
    oneTimePayment: 'Pago único de por vida',
    activateFor: 'ACTIVAR POR 7.99 USD',
    lifetimeSub: 'SUSCRIPCIÓN DE POR VIDA',
    goldFeatures: [
      "Control de gastos diarios y mensuales",
      "Alertas por Email y Notificaciones",
      "Sincronización en la nube ilimitada",
      "Sin anuncios ni interrupciones",
      "Auto-borrado de eventos pasados",
      "Importación de contactos ilimitada",
      "Temas personalizados (Modo Oscuro)",
      "Añadir recordatorios desde calendario"
    ],
    eventsForDay: 'Eventos para el',
    noEventsToday: 'Nada programado para hoy',
    deleteConfirm: '¿ELIMINAR RECORDATORIO?',
    autoDeleteConfirm: '¿ACTIVAR AUTO-BORRADO DE EVENTOS PASADOS?',
    importContactsConfirm: '¿QUIERES IMPORTAR LOS CUMPLEAÑOS DE TUS CONTACTOS?',
    emailConfirmTitle: 'PERMISO DE ALERTAS POR EMAIL',
    emailConfirmText: '¿Autorizas a My Days a enviar alertas a tu correo registrado?',
    emailConfirmNote: 'Las notificaciones del dispositivo seguirán activas.',
    yes: 'SÍ',
    no: 'NO',
    askFriends: 'CUMPLEAÑOS DE MIS AMIGOS',
    askFriendsSub: 'COPIA EL TEXTO Y ENVIALO A TUS AMIGOS',
    copiedToClipboard: '¡Texto copiado!',
    yourBirthday: 'CONFIRMA LA FECHA DE TU CUMPLEAÑOS',
    thanks: 'GRACIAS 🎂',
    happyBirthday: '¡FELIZ CUMPLEAÑOS!',
    version: 'VERSIÓN',
    min_suffix: 'MINUTOS',
    hour_suffix: 'HORAS',
    day_suffix: 'DÍA',
    days_suffix: 'DÍAS',
    reminderDetails: 'REMINDER DETAILS',
    desc_BIRTHDAYS: "Cumpleaños, aniversarios o fechas especiales para celebrar.",
    desc_DOCUMENTS: "Fecha de caducidad para documentos y trámites legales.",
    desc_SUBSCRIPTIONS: "Renovación de servicios de teléfono, web, TV o cualquier club.",
    desc_APPOINTMENTS: "Citas médicas, reuniones de trabajo o encuentros.",
    desc_NOTES: "Notas diarias, lista de la compra, anotaciones generales.",
    chooseColor: 'ELIGE COLOR DE LA NOTA',
    audioNote: 'NOTA DE VOZ',
    addFile: 'AÑADIR ARCHIVO',
    attachedFile: 'ARCHIVO ADJUNTO',
    deleteFileTitle: '¿ELIMINAR ARCHIVO?',
    deleteFileConfirm: '¿ESTÁS SEGURO DE QUE QUIERES ELIMINAR ESTE ARCHIVO?',
    deleteFileFinal: 'CONFIRMAR ELIMINACIÓN FINAL',
    noFile: 'SIN ADJUNTO',
    record: 'RECORD',
    stop: 'STOP',
    play: 'PLAY',
    recording: 'GRABANDO...',
    max30s: 'Máx. 30 segundos',
    desc_DNI_PASAPORTE: "Fecha de caducidad del DNI, pasaporte o cualquier documento personal.",
    desc_BANCO_TARJETAS: "Fecha de caducidad de tarjetas de crédito o débito.\nIMPORTANTE: Por seguridad, no introduzcas el número completo.",
    desc_VEHICULOS: "ITV, revisiones, cambios de aceite o seguro del vehículo.",
    desc_SEGUROS: "Pago de impuestos, tasas, contribuciones periódicas o seguros.",
    desc_TELEFONIA: "Renovación de contratos de teléfono o servicios de internet.",
    desc_WEB_APP: "Suscripciones a servicios web, aplicaciones o entretenimiento digital.",
    desc_TV_WIFI: "Plataformas de streaming, TV por cable o servicios de Wi-Fi.",
    desc_TIENDAS_CLUBS: "Tarjetas de fidelidad, cuotas de gimnasio o membresías.",
    desc_MEDICAS: "Citas médicas, visitas al dentista o especialistas de salud.",
    desc_TRABAJO: "Reuniones, entregas, eventos laborales, escolares o académicos.",
    desc_AMIGOS: "Amigos, peluquería, gimnaasio o viajes.",
    desc_FAMILIARES: "Eventos familiares, celebraciones o reuniones.",
    cardsNewReminder: 'CARDS NEW REMINDER',
    dailyExpenses: 'NUEVO GASTO',
    viewMyExpenses: 'VER MIS GASTOS',
    currencyLabel: 'Moneda',
    amount: 'CANTIDAD',
    category: 'CATEGORÍA',
    expensesOf: 'GASTOS DE',
    totalMonthly: 'TOTAL MENSUAL',
    expenseCategories: {
      SUPERMARKET: 'Supermercado',
      RESTAURANT: 'Restaurante',
      SHOPPING: 'Compras',
      WORK: 'Trabajo',
      ENTERTAINMENT: 'Entretenimiento',
      TRANSPORT: 'Transporte',
      HOME: 'Hogar',
      PETS: 'Mascotas',
      FUEL: 'Combustible',
      VEHICLES: 'Vehículos',
      SERVICES: 'Servicios',
      HEALTH: 'Salud',
      OTHERS: 'Otros'
    },
    purchaseHistory: 'PURCHASE HISTORY',
    transactionId: 'TRANSACTION ID',
    purchaseDate: 'FECHA COMPRA',
    notifyMethod: 'NOTIFICACIÓN MAIL',
    pushNotify: 'NOTIF. DISPOSITIVO',
    emailNotify: 'ALERTA EMAIL',
    profilePhoto: 'FOTO DE PERFIL',
    uploadPhoto: 'UPLOAD PHOTO',
    photoResolutionNote: 'La foto se guarda localmente en el caché de tu navegador.',
    sameDay: 'EL MISMO DÍA',
    generalNotifTime: 'HORA NOTIF.',
    generalNotifTimeDesc: 'Elige a qué hora quieres recibir tus alertas los días correspondientes.',
    selectTime: 'ELEGIR HORA',
    exportExpenses: 'EXPORTAR GASTOS',
    selectFormat: 'ELIGE FORMATO',
    excelFormat: 'EXCEL / CSV',
    pdfFormat: 'DOCUMENTO PDF',
    textFormat: 'ARCHIVO DE TEXTO',
    other: 'OTRO',
    info: 'INFORMACIÓN',
    seeTutorial: 'VER TUTORIAL'
  }
};

export const CATEGORY_DETAILS: Record<CategoryType, any> = {
  [CategoryType.BIRTHDAYS]: {
    icon: <Cake />,
    color: 'from-rose-400 to-rose-600',
    textColor: 'text-rose-600',
    lightColor: 'bg-rose-50'
  },
  [CategoryType.DOCUMENTS]: {
    icon: <ShieldCheck />,
    color: 'from-blue-400 to-blue-600',
    textColor: 'text-blue-600',
    lightColor: 'bg-blue-50'
  },
  [CategoryType.SUBSCRIPTIONS]: {
    icon: <Tv />,
    color: 'from-amber-400 to-amber-500',
    textColor: 'text-amber-600',
    lightColor: 'bg-amber-50'
  },
  [CategoryType.APPOINTMENTS]: {
    icon: <CalendarDays />,
    color: 'from-emerald-400 to-emerald-600',
    textColor: 'text-emerald-600',
    lightColor: 'bg-emerald-50'
  },
  [CategoryType.NOTES]: {
    icon: <StickyNote />,
    color: 'from-slate-400 to-slate-600',
    textColor: 'text-slate-600',
    lightColor: 'bg-slate-50'
  },
  [CategoryType.VIOLET]: {
    icon: <CreditCard />, 
    color: 'from-violet-400 to-violet-600',
    textColor: 'text-violet-600',
    lightColor: 'bg-violet-50'
  }
};

export const SUB_CATEGORY_DETAILS: Record<SubCategoryType, any> = {
  DNI_PASAPORTE: { icon: <User />, labelKey: 'sub_dni' },
  BANCO_TARJETAS: { icon: <CreditCard />, labelKey: 'sub_bank' },
  VEHICULOS: { icon: <Car />, labelKey: 'sub_vehicle' },
  SEGUROS: { icon: <FileText />, labelKey: 'sub_insur' },
  TELEFONIA: { icon: <Phone />, labelKey: 'sub_phone' },
  WEB_APP: { icon: <Globe />, labelKey: 'sub_web' },
  TV_WIFI: { icon: <TvSub />, labelKey: 'sub_tv' },
  TIENDAS_CLUBS: { icon: <ShoppingBag />, labelKey: 'sub_stores' },
  MEDICAS: { icon: <Stethoscope />, labelKey: 'sub_med' },
  TRABAJO: { icon: <Briefcase />, labelKey: 'sub_work' },
  AMIGOS: { icon: <Users />, labelKey: 'sub_friends' },
  FAMILIARES: { icon: <Heart />, labelKey: 'sub_fam' },
  OTRO: { icon: <FileText />, labelKey: 'other' }
};

export const SUB_MAP: Record<CategoryType, SubCategoryType[]> = {
  [CategoryType.BIRTHDAYS]: ['AMIGOS', 'FAMILIARES'],
  [CategoryType.DOCUMENTS]: ['DNI_PASAPORTE', 'BANCO_TARJETAS', 'VEHICULOS', 'SEGUROS'],
  [CategoryType.SUBSCRIPTIONS]: ['TELEFONIA', 'WEB_APP', 'TV_WIFI', 'TIENDAS_CLUBS'],
  [CategoryType.APPOINTMENTS]: ['MEDICAS', 'TRABAJO', 'AMIGOS', 'FAMILIARES'],
  [CategoryType.NOTES]: [],
  [CategoryType.VIOLET]: []
};
